[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "gK7LKdzB7mKMHGg7Tio7Yatjhrb6V3yAGkYTqbTSoKz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --esm -p ./tsconfig.json -t 1000000 tests/**/*.ts"
